# Generated by Django 4.1.4 on 2023-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
