# Generated by Django 4.1.4 on 2023-01-04 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feeds", "0003_feed_user"),
        ("reviews", "0002_review_created_review_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feed",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="feeds.feed"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
