# Generated by Django 4.1.4 on 2023-01-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_feed_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="feed",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
